image: julia:1.6  # Docker img of a system w/ Julia 1.6


# # # STAGES

# build stages execute sequentially; jobs within a stage execute parallel to one another
# every job is run on a new VM
stages:
  - build # wherein we check that the minimum build succeeds
  - test # wherein the full build is unit/doc/cross tested in parallel
  - deploy # wherein we build and deploy the documentation


# # # BUILD STAGE

minimal-build: # test minimal build, no Python
  stage: build
  script:
    - julia --project=@. -e 'import Pkg; Pkg.build("Xtals"); using Xtals'
  after_script: ## TODO remove. this is just to help debug artifact passing for the full build
    - ls -a $CI_PROJECT_DIR/..
    - echo $CI_PROJECT_DIR

# all jobs in next stage of pipeline need the things installed by quick_setup.jl
full-build: # full build for complete testing
  stage: build
  script:
    - julia --project=@. -e 'import Pkg; Pkg.build("Xtals")' # enforce priority of local Xtals
    - julia --project=@. quick_setup.jl # run the full installer script
    - julia --project=@. -e 'using Xtals' # make sure pkg loads in fresh session
  after_script:
    - ln -s ~/.julia $CI_PROJECT_DIR/.julia
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Manifest.toml
      - $CI_PROJECT_DIR/.julia/*


# # # TEST STAGE

artifact-testing: # check that previous build state has been preserved
  stage: test
  script:
    - julia --project=@. -e 'using Xtals'

unit-testing: # run all the unit tests
  stage: test
  before_script:
    - julia --project=@. quick_setup.jl
    - julia --project=@. -e 'import Pkg; Pkg.add("Documenter")'
    - julia --project=@. -e 'import Pkg; Pkg.add("FIGlet")'
  script:
    - julia --project=@. -e 'cd("test"); include("unit_tests.jl")'

docs-code-testing: # test the code examples in the docs
  stage: test
  before_script:
    - julia --project=@. -e 'import Pkg; Pkg.build("Xtals"); using Xtals'
    - julia --project=@. quick_setup.jl
    - julia --project=@. -e 'import Pkg; Pkg.add("Documenter")'
    - julia --project=@. -e 'import Pkg; Pkg.add("FIGlet")'
  script:
    - julia --project=@. -e 'cd("test"); include("doc_tests.jl")'

porousmaterials-testing: # check for breaking changes
  stage: test
  before_script:
    - julia --project=@. quick_setup.jl
  script:
    - julia --project=@. ./test/cross_dep.jl PorousMaterials

porematmod-testing: # check for breaking changes
  stage: test
  before_script:
    - julia --project=@. quick_setup.jl
  script:
    - julia --project=@. ./test/cross_dep.jl PoreMatMod


# # # DEPLOY STAGE

deploy-docs: # build and deploy the docs
  stage: deploy
  before_script:
    - julia --project=@. -e 'import Pkg; Pkg.add("Documenter")'
  script:
    - julia --project=@. ./docs/make.jl
