image: julia:1.6

# build stages execute sequentially; jobs within a stage execute in parallel
# every job is run on a new VM
stages:
  - prebuild # wherein we install Julia
  - build # wherein we set up the environment and build the package
  - test # wherein we run unit tests and doc-tests in parallel
  - crosstest # wherein we check for breaking changes vs. dev branches of key downstream packages
  - deploy # wherein we build and deploy the documentation


# # # BUILD STAGE

build-pkg: # test building sans Python
  stage: build
  script:
    - julia --project -e 'import Pkg; Pkg.build("Xtals")'

build-script: # test building w/ Python
  stage: build
  script:
    - julia --project quick_setup.jl
  artifacts:
    paths:
      - .julia # pass Julia environment to downstream jobs


# # # TEST STAGE

test-unit: # run all the unit tests
  stage: test
  script:
    - julia --project ./test/unit_tests.jl

test-docs: # test the code examples in the docs
  stage: test
  script:
    - julia --project -e 'import Pkg; Pkg.add("Documenter");
    - julia --project -e 'include("doc_tests.jl")'


# # # CROSSTEST STAGE

crosstest-porousmaterials: # check for breaking changes
  stage: crosstest
  script:
    - julia ./test/cross_dep.jl PorousMaterials

crosstest-porematmod: # check for breaking changes
  stage: crosstest
  script:
    - julia ./test/cross_dep.jl PoreMatMod


# # # DEPLOY STAGE

deploy-docs: # build and deploy the docs
  stage: deploy
  script:
    - julia ./docs/make.jl
