# set operating system to Ubuntu 16.04
os: linux
dist: xenial

# install additional package(s)
addons:
  apt:
    packages:
      - libhdf5-serial-dev

# get Julia 1.6
language: julia
julia: 1.6

# set codecov env var
codecov: true

# run build jobs
jobs:
  include:
    # install deps
    - stage: Setup
    script:
      - julia quick_setup.jl
      - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("Coverage")'
    skip_cleanup: true

    # unit tests, test coverage, and docs building
    - stage: Testing & Documentation
    # run unit tests and record test coverage
    script: julia --project --check-bounds=yes -e 'import Pkg; Pkg.test("Xtals", coverage=true)'
    # build/deploy docs and upload test coverage results
    after_success:
      - cd ./test && julia --project ./docs/make.jl
      - julia --project -e 'using Coverage; Codecov.submit(process_folder())'
    skip_cleanup: true

    # cross-test w/ dependent libraries
    - stage: Cross-Testing
    # run each test in parallel
    script: julia --project ./test/cross_dep.jl PorousMaterials
    script: julia --project ./test/cross_dep.jl PoreMatMod
    skip_cleanup: true

# whether or not to send an email on success/failure
notifications:
  email: false # I think they're annoying
