#site_name:        Xtals.jl
site_name:        ""
repo_url:         https://github.com/SimonEnsemble/Xtals.jl
site_description: Documentation for the julia package Xtals.jl
site_author:      SimonEnsemble

theme: windmill

extra_css:
  - assets/flux.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
  - mathjax-config.js

markdown_extensions:
  - pymdownx.arithmatex
  - extra
  - tables
  - fenced_code
  - toc:
      permalink: '#'
  #- toc:
  #    baselevel: 1
  #- mdx_math
extra:
  logo: assets/logo.jpg

docs_dir: 'build'
