name: CI Testing

on:
  push: # run on push to master
    branches: [ master ]
  pull_request: # run on PR against master
    branches: [ master ]
  workflow_dispatch: # run on button-press in Actions tab

env:
  julia_version: '1.6.3' # julia version to use on all runners

jobs: # run in parallel within workflow
  minimal-build: # test package building w/o optional feature Python dependencies
    runs-on: ubuntu-latest
    steps: # run in series within job
      - uses: actions/checkout@v2 # check out the code
      - uses: julia-actions/setup-julia@latest # set up Julia
        with:
          version: ${{julia_version}}
      - uses: julia-actions/julia-buildpkg@latest # test building
      
  unit-tests: # run unit tests on full build
    needs: minimal-build # the minimal build must be successful before this job will run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{julia_version}}
      - name: setup # install package and all dependencies
        run: |
          julia --project quick_setup.jl
          julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("FIGlet")'
      - name: test # run the unit tests
        run: |
          julia --project -e 'cd("test"); include("unit_tests.jl")'
  
  doc-tests: # run doctests
    needs: minimal-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{julia_version}}
      - name: setup
        run: |
          julia --project quick_setup.jl
          julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("FIGlet")'
      - name: test
        run: |
          julia --project -e 'cd("test"); include("doc_tests.jl")'
          
  porousmaterials: # cross-test PorousMaterials for breaking changes
    needs: minimal-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{julia_version}}
      - name: setup
        run: |
          julia --project quick_setup.jl
          julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("FIGlet")'
      - name: test # use the cross_dep.jl script to run unit/doc tests on the dev branch of the specified package
        run: |
          julia --project ./test/cross_dep.jl PorousMaterials

  porematmod:
    needs: minimal-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{julia_version}}
      - name: setup
        run: |
          julia --project quick_setup.jl
          julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("FIGlet")'
      - name: test
        run: |
          julia --project ./test/cross_dep.jl PoreMatMod
          
  deploy-docs:
    needs: [unit-tests, doc-tests, porousmaterials, porematmod]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{julia_version}}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest # deploy the docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOCUMENTER_KEY: ${{secrets.DOCUMENTER_KEY}}
